name: Configurando a página PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalando dependências
        run: composer install --no-dev --optimize-autoloader

      - name: Build páginas
        run: composer run-script build

      - name: Verificar conteúdo da pasta ./public
        run: ls -la ./public

      - name: Carregando artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
    steps:
      - name: Verificar artefatos carregados
        uses: actions/download-artifact@v4
        with:
          path: ./public
      - name: Conferir conteúdo dos artefatos
        run: ls -la ./public
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          #debug: true
